#! /bin/bash

SCRIPT_DIR="$(dirname $0)"
DOTFILES_HOME="${HOME}/.dotfiles/home"

link() {
  if [ "$(readlink $HOME/$1)" == "${DOTFILES_HOME}/$1" ]; then
    return;
  elif [ -f "$HOME/$1" ]; then
    echo "Oh dear. I couldn't symlink $1 because it's already a file."
    echo "\`rm $HOME/$1\` and rerun this script to establish the link."
  else
    ln -s "${DOTFILES_HOME}/$1" "${HOME}/$1"
  fi
}

setup_vim() {
  link ".vimrc"

  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim +"PlugInstall --sync" +qa
  mkdir -p ~/.vim/tmp
}

setup_tmux() {
  sudo apt-get install tmux
  link ".tmux.conf"
}

install_packer() {
  local version="1.3.5"
  if [ -f /usr/local/bin/packer ] && [ "$version" == "$(packer --version)" ]; then
    return;
  fi

  sudo apt-get install unzip
  cd $HOME
  curl -fLo packer.zip \
    "https://releases.hashicorp.com/packer/${version}/packer_${version}_linux_amd64.zip"
  unzip packer.zip -d .
  sudo mv packer /usr/local/bin/
  rm packer.zip
}

install_rbenv() {
  if [ -d ~/.rbenv ]; then
    return;
  fi

  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  ~/.rbenv/bin/rbenv init
  mkdir -p "$(rbenv root)"/plugins
  git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
}

install_ruby_build_dependencies() {
  sudo apt-get install -y \
    build-essential \
    libreadline6-dev \
    zlib1g-dev \
    libssl-dev
}

install_rubies() {
  install_rbenv
  install_ruby_build_dependencies
  rbenv install -s -v 2.6.2
}

setup_vim
setup_tmux
link ".bash_aliases"
link ".gitconfig"
install_packer
install_rubies
