#! /bin/bash

SCRIPT_DIR="$(dirname $0)"

link() {
  echo "Working in $SCRIPT_DIR to link $1"
  ln -s "${HOME}/.dotfiles/home/$1" "${HOME}/$1"
}

setup_vim() {
  link ".vimrc"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +"PlugInstall --sync" +qa
}

setup_tmux() {
  sudo apt-get install tmux
  link ".tmux.conf"
}

install_packer() {
  sudo apt-get install unzip
  cd $HOME
  curl -fLo packer.zip \
    https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip
  unzip packer.zip -d .
  sudo mv packer /usr/local/bin/
  rm packer.zip
}

setup_vim
setup_tmux
link ".bash_aliases"
link ".gitconfig"
install_packer
